# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20171130031450) do

  create_table "items", force: :cascade do |t|
    t.string   "client_ssn"
    t.string   "client_name"
    t.string   "case_type"
    t.string   "status"
    t.datetime "date_opened"
    t.datetime "date_closed"
    t.datetime "created_at",             null: false
    t.datetime "updated_at",             null: false
    t.string   "case_id"
    t.string   "name_of_clinic"
    t.string   "grant_year"
    t.string   "document1_file_name"
    t.string   "document1_content_type"
    t.integer  "document1_file_size"
    t.datetime "document1_updated_at"
    t.string   "document2_file_name"
    t.string   "document2_content_type"
    t.integer  "document2_file_size"
    t.datetime "document2_updated_at"
    t.string   "document3_file_name"
    t.string   "document3_content_type"
    t.integer  "document3_file_size"
    t.datetime "document3_updated_at"
    t.string   "document4_file_name"
    t.string   "document4_content_type"
    t.integer  "document4_file_size"
    t.datetime "document4_updated_at"
    t.string   "document5_file_name"
    t.string   "document5_content_type"
    t.integer  "document5_file_size"
    t.datetime "document5_updated_at"
    t.string   "B_1"
    t.string   "B_2"
    t.string   "B_3"
    t.string   "B_4"
    t.string   "B_5"
    t.string   "B_6"
    t.string   "B_7"
    t.string   "B_8"
    t.string   "B_9"
    t.string   "B_10"
    t.string   "B_11"
    t.string   "B_12"
    t.string   "B_13"
    t.string   "B_14"
    t.string   "B_15"
    t.string   "B_16"
    t.string   "B_17"
    t.string   "B_18"
    t.string   "B_19"
    t.string   "B_20"
    t.string   "B_21"
    t.string   "B_22"
    t.string   "B_23"
    t.string   "B_24"
    t.string   "B_25"
    t.string   "B_26"
    t.string   "B_27"
    t.string   "B_28"
    t.string   "B_29"
    t.string   "B_30"
    t.string   "B_31"
    t.string   "B_32"
    t.string   "B_33"
    t.string   "B_34"
    t.string   "B_35"
    t.string   "B_36"
    t.string   "B_37"
    t.string   "B_38"
    t.string   "B_39"
    t.string   "B_40"
    t.string   "B_41"
    t.string   "B_42"
    t.string   "B_43"
    t.string   "B_44"
    t.string   "B_45"
    t.string   "B_46"
    t.string   "B_47"
    t.string   "B_48"
    t.string   "B_49"
    t.string   "B_50"
    t.string   "B_51"
    t.string   "B_52"
    t.string   "B_53"
    t.string   "B_54"
    t.string   "B_55"
    t.string   "B_56"
    t.string   "B_57"
    t.string   "B_58"
    t.string   "B_59"
    t.string   "B_60"
    t.string   "B_61"
    t.string   "B_62"
    t.string   "B_total"
    t.string   "K_1A"
    t.string   "K_1B"
    t.string   "K_1C"
    t.string   "K_1D"
    t.string   "K_1E"
    t.string   "K_2A"
    t.string   "K_2B"
    t.string   "K_2C"
    t.string   "K_2D"
    t.string   "K_2E"
    t.string   "K_2F"
    t.string   "K_2G"
    t.string   "K_2H"
    t.string   "K_2I"
    t.string   "K_2J"
    t.string   "K_2K"
    t.string   "K_2L"
    t.string   "K_2M"
    t.string   "K_2N"
    t.string   "K_2O"
    t.string   "K_2P"
    t.string   "K_2Q"
    t.string   "K_2R"
    t.string   "K_2S"
    t.string   "K_2T"
    t.string   "K_2U"
    t.string   "K_2V"
    t.string   "K_2W"
    t.string   "K_2X"
    t.string   "K_2Y"
    t.string   "K_2Z"
    t.string   "K_2AA"
    t.string   "K_total"
    t.string   "K_3"
    t.string   "K_4"
    t.string   "K_5"
    t.string   "K_6"
    t.string   "K_7"
    t.string   "K_8"
    t.string   "K_9"
    t.string   "K_10"
    t.string   "K_12"
    t.string   "K_13"
    t.string   "K_14"
    t.string   "K_15A"
    t.string   "K_15B"
    t.string   "K_15C"
    t.string   "K_15D"
  end

  create_table "settings", force: :cascade do |t|
    t.string   "var",                   null: false
    t.text     "value"
    t.integer  "thing_id"
    t.string   "thing_type", limit: 30
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "settings", ["thing_type", "thing_id", "var"], name: "index_settings_on_thing_type_and_thing_id_and_var", unique: true

end
