class AddRefactoredFieldsToItem < ActiveRecord::Migration
  def change
    add_column :items, :B_1, :string
    add_column :items, :B_2, :string
    add_column :items, :B_3, :string
    add_column :items, :B_4, :string
    add_column :items, :B_5, :string
    add_column :items, :B_6, :string
    add_column :items, :B_7, :string
    add_column :items, :B_8, :string
    add_column :items, :B_9, :string
    add_column :items, :B_10, :string
    add_column :items, :B_11, :string
    add_column :items, :B_12, :string
    add_column :items, :B_13, :string
    add_column :items, :B_14, :string
    add_column :items, :B_15, :string
    add_column :items, :B_16, :string
    add_column :items, :B_17, :string
    add_column :items, :B_18, :string
    add_column :items, :B_19, :string
    add_column :items, :B_20, :string
    add_column :items, :B_21, :string
    add_column :items, :B_22, :string
    add_column :items, :B_23, :string
    add_column :items, :B_24, :string
    add_column :items, :B_25, :string
    add_column :items, :B_26, :string
    add_column :items, :B_27, :string
    add_column :items, :B_28, :string
    add_column :items, :B_29, :string
    add_column :items, :B_30, :string
    add_column :items, :B_31, :string
    add_column :items, :B_32, :string
    add_column :items, :B_33, :string
    add_column :items, :B_34, :string
    add_column :items, :B_35, :string
    add_column :items, :B_36, :string
    add_column :items, :B_37, :string
    add_column :items, :B_38, :string
    add_column :items, :B_39, :string
    add_column :items, :B_40, :string
    add_column :items, :B_41, :string
    add_column :items, :B_42, :string
    add_column :items, :B_43, :string
    add_column :items, :B_44, :string
    add_column :items, :B_45, :string
    add_column :items, :B_46, :string
    add_column :items, :B_47, :string
    add_column :items, :B_48, :string
    add_column :items, :B_49, :string
    add_column :items, :B_50, :string
    add_column :items, :B_51, :string
    add_column :items, :B_52, :string
    add_column :items, :B_53, :string
    add_column :items, :B_54, :string
    add_column :items, :B_55, :string
    add_column :items, :B_56, :string
    add_column :items, :B_57, :string
    add_column :items, :B_58, :string
    add_column :items, :B_59, :string
    add_column :items, :B_60, :string
    add_column :items, :B_61, :string
    add_column :items, :B_62, :string
    add_column :items, :B_total, :string
    add_column :items, :K_1A, :string
    add_column :items, :K_1B, :string
    add_column :items, :K_1C, :string
    add_column :items, :K_1D, :string
    add_column :items, :K_1E, :string
    add_column :items, :K_2A, :string
    add_column :items, :K_2B, :string
    add_column :items, :K_2C, :string
    add_column :items, :K_2D, :string
    add_column :items, :K_2E, :string
    add_column :items, :K_2F, :string
    add_column :items, :K_2G, :string
    add_column :items, :K_2H, :string
    add_column :items, :K_2I, :string
    add_column :items, :K_2J, :string
    add_column :items, :K_2K, :string
    add_column :items, :K_2L, :string
    add_column :items, :K_2M, :string
    add_column :items, :K_2N, :string
    add_column :items, :K_2O, :string
    add_column :items, :K_2P, :string
    add_column :items, :K_2Q, :string
    add_column :items, :K_2R, :string
    add_column :items, :K_2S, :string
    add_column :items, :K_2T, :string
    add_column :items, :K_2U, :string
    add_column :items, :K_2V, :string
    add_column :items, :K_2W, :string
    add_column :items, :K_2X, :string
    add_column :items, :K_2Y, :string
    add_column :items, :K_2Z, :string
    add_column :items, :K_2AA, :string
    add_column :items, :K_T, :string
    add_column :items, :K_3, :string
    add_column :items, :K_4, :string
    add_column :items, :K_5, :string
    add_column :items, :K_6, :string
    add_column :items, :K_7, :string
    add_column :items, :K_8, :string
    add_column :items, :K_9, :string
    add_column :items, :K_10, :string
    add_column :items, :K_12, :string
    add_column :items, :K_13, :string
    add_column :items, :K_14, :string
    add_column :items, :K_15A, :string
    add_column :items, :K_15B, :string
    add_column :items, :K_15C, :string
    add_column :items, :K_15D, :string
  end
end
